# Generated by Django 2.2.12 on 2020-06-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_wizard', '0002_auto_20190306_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifier',
            name='allow_null',
            field=models.BooleanField(default=False),
        ),
    ]
