# Generated by Django 2.2.12 on 2020-07-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_wizard', '0005_auto_20200623_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identifier',
            name='allow_null',
        ),
    ]
